### ISSUE TITLE
Automation not working when one of the connect Machines have no recepie

### ISSUE THREAD

**Issue by sebbi08** [Daschi1/automatic-logistic-chests#1]
![image](https://user-images.githubusercontent.com/9070136/120318553-4752be80-c2e0-11eb-8b3f-492a3f21530d.png)

in the following setup the automation is not working so it is not setting anything to the requester.
The provider limitation is working fine

**Comment by Daschi1** [comment]
Thanks, I merged your pull request and published an update.

**Comment by sebbi08** [comment]
Thank you too
