### ISSUE TITLE
Small improvement

### ISSUE THREAD

**Issue by SixFive7** [Daschi1/automatic-logistic-chests#3]
Hi, I added a small improvement to your mod. Because I want to continue our server with my friends I put it here: https://mods.factorio.com/mod/automatic-logistic-chests-v657. Feel free to copy if you like. If you integrate it I will ofc remove my version to cleanup any clutter ;-)

**Comment by Daschi1** [comment]
Thank you for contributing. Unfortunately I couldn't find your source code anywhere, if you could provide it I'd be happy to integrate it into my version.

**Comment by SixFive7** [comment]
Hi, I just put my changes in a ready to go pull request https://github.com/Daschi1/automatic-logistic-chests/pull/4. Hope that helps.
Thanks for making and maintaining these mods!

**Comment by Daschi1** [comment]
Thank you again for contributing.
