### ISSUE TITLE
[Request] Support for chests from the mod AAI Containers & Warehouses

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Daschi1/automatic-logistic-chests#5]
Please consider adding support for chests and warehouses from the [AAI Containers & Warehouses mod](https://mods.factorio.com/mod/aai-containers)

**Comment by Daschi1** [comment]
Sorry for the late reply, but I don't have time at the moment to continue developing the mod, since I am studying and that is taking up a considering amount of my time. I hope you can understand.

**Comment by Eldrinn-Elantey** [comment]
I understand. Have a good study. 

My need for this change has disappeared since I switched to another mod with a similar function.

Anyway, your mod is useful, I'm sure it helped a lot to make the game easier and more convenient.
